spring.application.name=ik-portal
server.port=8080

# --- PostgreSQL DB bilgileri ---
spring.datasource.url=jdbc:postgresql://localhost:5432/ikportal
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# --- Thymeleaf ---
spring.thymeleaf.cache=false

# --- Web ---
spring.mvc.format.date=yyyy-MM-dd
spring.web.resources.cache.period=0
server.servlet.session.timeout=60m
server.error.whitelabel.enabled=true

# --- Loglama ---
logging.level.com.pmt.ikportal=INFO
